export function getDom() {
  const canvas = document.getElementById("c");
  const ctx = canvas.getContext("2d", { alpha: false });

  return {
    canvas,
    ctx,
    btnConnect: document.getElementById("btnConnect"),
    btnDisconnect: document.getElementById("btnDisconnect"),
    btnStart: document.getElementById("btnStart"),
    btnStop: document.getElementById("btnStop"),
    btnCenter: document.getElementById("btnCenter"),
    btnZoomOut: document.getElementById("btnZoomOut"),
    btnZoomIn: document.getElementById("btnZoomIn"),
    btnZoomReset: document.getElementById("btnZoomReset"),
    pill: document.getElementById("pill"),
    statusLine: document.getElementById("statusLine"),
    statusSub: document.getElementById("statusSub"),
    fps: document.getElementById("fps"),
    fpsVal: document.getElementById("fpsVal"),
    gain: document.getElementById("gain"),
    gainVal: document.getElementById("gainVal"),
    gamma: document.getElementById("gamma"),
    gammaVal: document.getElementById("gammaVal"),
    lookOn: document.getElementById("lookOn"),
    lookHue: document.getElementById("lookHue"),
    lookHueVal: document.getElementById("lookHueVal"),
    lookSat: document.getElementById("lookSat"),
    lookSatVal: document.getElementById("lookSatVal"),
    snapOn: document.getElementById("snapOn"),
    snapMm: document.getElementById("snapMm"),
    mm2px: document.getElementById("mm2px"),
    showRings: document.getElementById("showRings"),
    showIndex: document.getElementById("showIndex"),
    showGrid: document.getElementById("showGrid"),
    selBoard: document.getElementById("selBoard"),
    rotDeg: document.getElementById("rotDeg"),
    posX: document.getElementById("posX"),
    posY: document.getElementById("posY"),
    btnResetBoard: document.getElementById("btnResetBoard"),
    btnResetAll: document.getElementById("btnResetAll"),
    btnExport: document.getElementById("btnExport"),
    btnCopy: document.getElementById("btnCopy"),
    btnImport: document.getElementById("btnImport"),
    fileInput: document.getElementById("fileInput"),
    originX: document.getElementById("originX"),
    originY: document.getElementById("originY"),
    showOrigin: document.getElementById("showOrigin"),
    originSnap: document.getElementById("originSnap"),
    btnOriginToSelected: document.getElementById("btnOriginToSelected"),
    btnOriginZero: document.getElementById("btnOriginZero"),
    btnCamStart: document.getElementById("btnCamStart"),
    btnCamStop: document.getElementById("btnCamStop"),
    trackEnable: document.getElementById("trackEnable"),
    panelLight: document.getElementById("panelLight"),
    trackDebug: document.getElementById("trackDebug"),
    trackSmooth: document.getElementById("trackSmooth"),
    trackSmoothVal: document.getElementById("trackSmoothVal"),
    trackSens: document.getElementById("trackSens"),
    trackSensVal: document.getElementById("trackSensVal"),
    trackXMin: document.getElementById("trackXMin"),
    trackXMax: document.getElementById("trackXMax"),
    trackYMin: document.getElementById("trackYMin"),
    trackYMax: document.getElementById("trackYMax"),
    trackMirrorX: document.getElementById("trackMirrorX"),
    trackInvertY: document.getElementById("trackInvertY"),
    trackUseSse: document.getElementById("trackUseSse"),
    trackSseUrl: document.getElementById("trackSseUrl"),
    trackSseCam: document.getElementById("trackSseCam"),
    trackSseStatus: document.getElementById("trackSseStatus"),
    selInfo: document.getElementById("selInfo"),
    originInfo: document.getElementById("originInfo"),
    trackInfo: document.getElementById("trackInfo"),
    mouseInfo: document.getElementById("mouseInfo"),
    dropInfo: document.getElementById("dropInfo"),
    mInfo: document.getElementById("mInfo"),
    fxSelect: document.getElementById("fxSelect"),
    btnFxResetParams: document.getElementById("btnFxResetParams"),
    btnFxResetState: document.getElementById("btnFxResetState"),
    fxParams: document.getElementById("fxParams"),
    camOverlay: document.getElementById("camOverlay"),
    camVideo: document.getElementById("camVideo"),
    camDebugCanvas: document.getElementById("camDebugCanvas"),
  };
}
